version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"      # Porta do RabbitMQ para comunicação
      - "15672:15672"    # Porta de gerenciamento (interface web)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  votacao-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"     # Porta do Spring Boot
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
